#!/bin/bash

#
# This script forces 2nd party resolution from the server
# It delegates to the new virtual mono-repo client
#

WORKSPACE_DIR="${PWD}"
while [[ "${WORKSPACE_DIR}" != / ]]; do
    if [[ -e "${WORKSPACE_DIR}/WORKSPACE" ]]; then
      break;
    fi
    WORKSPACE_DIR="$(dirname "${WORKSPACE_DIR}")"
done

source ${WORKSPACE_DIR}/tools/vmr pull
